func main  { 
	try { 
		1/0
	catch 
		? :error
	} 
} 
func one  { 
	? :one
} 
